version: "3"
virtualmachines:
- name: server
  image: instruqt-hashicorp/ubuntu-2004-base
  shell: /bin/bash -l
  environment:
    MONGO_URL: mongodb://localhost:27017/
    NODE_ENV: production
    PORT: "3001"
  machine_type: n1-standard-1
